### ISSUE TITLE
Folders tree at the left

### ISSUE THREAD

**Issue by apischan** [skylerlee/zeta-zsh-theme#2]
Hi! Nice theme!
Could you point me how I can get the same folders tree like on your screenshot?
Thanks in advance!

**Comment by skylerlee** [comment]
Sorry for late reply. In fact, the folder tree is the tree view of Atom editor, because I'm using atom-term2 plugin for terminal emulation. It might be a little misleading in some ways.

Anyway, I think terminal multiplexer might be helpful for this.

**Comment by skylerlee** [comment]
Updated the screenshot.
