### ISSUE TITLE
Mintty colors

### ISSUE THREAD

**Issue by inrumi** [skylerlee/zeta-zsh-theme#3]
Which colors do you use in your screenshot? it looks like https://github.com/dracula/mintty and I have tried them bu they don't look equal.

**Comment by skylerlee** [comment]
I use [iTerm2-Color-Schemes](https://github.com/mbadolato/iTerm2-Color-Schemes) on MacOS. And yes, I use the [dracula colors](https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/schemes/Dracula.itermcolors).

Hope this helps.
