### ISSUE TITLE
iterm2 color scheme

### ISSUE THREAD

**Issue by peleusj** [skylerlee/zeta-zsh-theme#4]
What is the current iterm2 color scheme in the screenshot, think it is quite awesome, it is not dracula colors any more right?

**Comment by CoreyMcDonald** [comment]
I second this @peleusj !   The closest I have been able to come to is Elemental from [https://iterm2colorschemes.com/](url)

**Comment by peleusj** [comment]
I think I just find the right color scheme, it is Gruvbox Dark, get it from the https://iterm2colorschemes.com/, see more at https://github.com/morhetz/gruvbox.
